version : '4'

services:
  mysql:
    image: mysql:5.6
    container_name: order-service-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

