spring.application.name=inventory-service
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
server.port=8083


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
